import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { DashboardProvider } from "@/context/DashboardContext";
import Sidebar from "@/components/Sidebar";
import Chatbot from "@/components/Chatbot";
import HeaderWrapper from "@/components/HeaderWrapper"; // Need to create this to consume context

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background">
        <DashboardProvider>
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 p-8 overflow-y-auto h-screen">
              <div className="max-w-7xl mx-auto flex flex-col gap-8">
                <HeaderWrapper />
                {children}
              </div>
            </main>
            <Chatbot />
          </div>
        </DashboardProvider>
      </body>
    </html>
  );
}
